//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:2.0.50727.3082
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;
using System.Collections.Generic;
// 
// This source code was auto-generated by xsd, Version=2.0.50727.42.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class Picture {

    static public implicit operator Picture(CheezAPI cheezApi) {
        return cheezApi.Picture;
    }
    private string pictureIdField;
    
    private string attributionField;
    
    private string attributionUrlField;
    
    private string pictureImageUrlField;
    
    private string thumbnailImageUrlField;
    
    private string userIdField;
    
    private string userNameField;
    
    private string picturePageUrlField;
    
    private string timeStampField;
    
    private string lolIdField;
    
    private string lolImageUrlField;
    
    private string lolPageUrlField;
    
    private string fullTextField;
    
    private string clientIdField;
    
    private string titleField;
    
    private string descriptionField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string PictureId {
        get {
            return this.pictureIdField;
        }
        set {
            this.pictureIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Attribution {
        get {
            return this.attributionField;
        }
        set {
            this.attributionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string AttributionUrl {
        get {
            return this.attributionUrlField;
        }
        set {
            this.attributionUrlField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string PictureImageUrl {
        get {
            return this.pictureImageUrlField;
        }
        set {
            this.pictureImageUrlField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ThumbnailImageUrl {
        get {
            return this.thumbnailImageUrlField;
        }
        set {
            this.thumbnailImageUrlField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string UserId {
        get {
            return this.userIdField;
        }
        set {
            this.userIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string UserName {
        get {
            return this.userNameField;
        }
        set {
            this.userNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string PicturePageUrl {
        get {
            return this.picturePageUrlField;
        }
        set {
            this.picturePageUrlField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string TimeStamp {
        get {
            return this.timeStampField;
        }
        set {
            this.timeStampField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string LolId {
        get {
            return this.lolIdField;
        }
        set {
            this.lolIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string LolImageUrl {
        get {
            return this.lolImageUrlField;
        }
        set {
            this.lolImageUrlField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string LolPageUrl {
        get {
            return this.lolPageUrlField;
        }
        set {
            this.lolPageUrlField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string FullText {
        get {
            return this.fullTextField;
        }
        set {
            this.fullTextField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ClientId {
        get {
            return this.clientIdField;
        }
        set {
            this.clientIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Title {
        get {
            return this.titleField;
        }
        set {
            this.titleField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class Fail {

    static public implicit operator Fail(CheezAPI cheezApi) {
        return (cheezApi != null) ? cheezApi.Fail : null;
    }
    private string failureMessageField;
    
    private string failureDetailField;
    
    private string failureEventIdField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string FailureMessage {
        get {
            return this.failureMessageField;
        }
        set {
            this.failureMessageField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string FailureDetail {
        get {
            return this.failureDetailField;
        }
        set {
            this.failureDetailField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string FailureEventId {
        get {
            return this.failureEventIdField;
        }
        set {
            this.failureEventIdField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class Hai {
    
    static public implicit operator Hai(CheezAPI cheezApi) {
        return (cheezApi!= null) ? cheezApi.Hai : null;
    }
    
    private string greetingField;
    
    private string descriptionField;
    
    private string serverTimeField;
    
    private string versionField;
    
    private string environmentField;
    
    private string methodField;
    
    private string developerKeyInfoField;
    
    private string clientIdInfoField;
    
    private string authTokenInfoField;
    
    private HaiHeadersHttpHeader[] headersField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Greeting {
        get {
            return this.greetingField;
        }
        set {
            this.greetingField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ServerTime {
        get {
            return this.serverTimeField;
        }
        set {
            this.serverTimeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Version {
        get {
            return this.versionField;
        }
        set {
            this.versionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Environment {
        get {
            return this.environmentField;
        }
        set {
            this.environmentField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Method {
        get {
            return this.methodField;
        }
        set {
            this.methodField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string DeveloperKeyInfo {
        get {
            return this.developerKeyInfoField;
        }
        set {
            this.developerKeyInfoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ClientIdInfo {
        get {
            return this.clientIdInfoField;
        }
        set {
            this.clientIdInfoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string AuthTokenInfo {
        get {
            return this.authTokenInfoField;
        }
        set {
            this.authTokenInfoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute("HttpHeader", typeof(HaiHeadersHttpHeader), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
    public HaiHeadersHttpHeader[] Headers {
        get {
            return this.headersField;
        }
        set {
            this.headersField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class HaiHeadersHttpHeader {
    
    private string keyField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string key {
        get {
            return this.keyField;
        }
        set {
            this.keyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class Lol {

    static public implicit operator Lol(CheezAPI cheezApi) {
        return cheezApi.Lol;
    }

    private string lolIdField;
    
    private string lolImageUrlField;
    
    private string thumbnailImageUrlField;
    
    private string lolPageUrlField;
    
    private string fullTextField;
    
    private string clientIdField;
    
    private string pictureIdField;
    
    private string pictureImageUrlField;
    
    private string userIdField;
    
    private string titleField;
    
    private string descriptionField;
    
    private string timeStampField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string LolId {
        get {
            return this.lolIdField;
        }
        set {
            this.lolIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string LolImageUrl {
        get {
            return this.lolImageUrlField;
        }
        set {
            this.lolImageUrlField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ThumbnailImageUrl {
        get {
            return this.thumbnailImageUrlField;
        }
        set {
            this.thumbnailImageUrlField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string LolPageUrl {
        get {
            return this.lolPageUrlField;
        }
        set {
            this.lolPageUrlField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string FullText {
        get {
            return this.fullTextField;
        }
        set {
            this.fullTextField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ClientId {
        get {
            return this.clientIdField;
        }
        set {
            this.clientIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string PictureId {
        get {
            return this.pictureIdField;
        }
        set {
            this.pictureIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string PictureImageUrl {
        get {
            return this.pictureImageUrlField;
        }
        set {
            this.pictureImageUrlField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string UserId {
        get {
            return this.userIdField;
        }
        set {
            this.userIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Title {
        get {
            return this.titleField;
        }
        set {
            this.titleField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string TimeStamp {
        get {
            return this.timeStampField;
        }
        set {
            this.timeStampField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class Lols {

    static public implicit operator Lols(CheezAPI cheezApi) {
        return (cheezApi != null) ? cheezApi.Lols : null;
    }   
   
    private List<LolsRandomPicture> randomField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute("Picture", typeof(LolsRandomPicture), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
    public List<LolsRandomPicture> Random {
        get {
            return this.randomField;
        }
        set {
            this.randomField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class LolsRandomPicture {
    
    private string pictureIdField;
    
    private string attributionField;
    
    private string attributionUrlField;
    
    private string pictureImageUrlField;
    
    private string thumbnailImageUrlField;
    
    private string userIdField;
    
    private string userNameField;
    
    private string picturePageUrlField;
    
    private string timeStampField;
    
    private string lolIdField;
    
    private string lolImageUrlField;
    
    private string lolPageUrlField;
    
    private string fullTextField;
    
    private string clientIdField;
    
    private string titleField;
    
    private string descriptionField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string PictureId {
        get {
            return this.pictureIdField;
        }
        set {
            this.pictureIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Attribution {
        get {
            return this.attributionField;
        }
        set {
            this.attributionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string AttributionUrl {
        get {
            return this.attributionUrlField;
        }
        set {
            this.attributionUrlField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string PictureImageUrl {
        get {
            return this.pictureImageUrlField;
        }
        set {
            this.pictureImageUrlField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ThumbnailImageUrl {
        get {
            return this.thumbnailImageUrlField;
        }
        set {
            this.thumbnailImageUrlField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string UserId {
        get {
            return this.userIdField;
        }
        set {
            this.userIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string UserName {
        get {
            return this.userNameField;
        }
        set {
            this.userNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string PicturePageUrl {
        get {
            return this.picturePageUrlField;
        }
        set {
            this.picturePageUrlField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string TimeStamp {
        get {
            return this.timeStampField;
        }
        set {
            this.timeStampField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string LolId {
        get {
            return this.lolIdField;
        }
        set {
            this.lolIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string LolImageUrl {
        get {
            return this.lolImageUrlField;
        }
        set {
            this.lolImageUrlField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string LolPageUrl {
        get {
            return this.lolPageUrlField;
        }
        set {
            this.lolPageUrlField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string FullText {
        get {
            return this.fullTextField;
        }
        set {
            this.fullTextField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ClientId {
        get {
            return this.clientIdField;
        }
        set {
            this.clientIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Title {
        get {
            return this.titleField;
        }
        set {
            this.titleField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class Pictures {


    static public implicit operator Pictures(CheezAPI cheezApi) {
        return cheezApi.Pictures;
    }


    private List<PicturesRandomPicture> randomField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute("Picture", typeof(PicturesRandomPicture), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
    public List<PicturesRandomPicture> Random {
        get {
            return this.randomField;
        }
        set {
            this.randomField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class PicturesRandomPicture {
    
    private string pictureIdField;
    
    private string attributionField;
    
    private string attributionUrlField;
    
    private string pictureImageUrlField;
    
    private string thumbnailImageUrlField;
    
    private string userIdField;
    
    private string userNameField;
    
    private string picturePageUrlField;
    
    private string timeStampField;
    
    private string lolIdField;
    
    private string lolImageUrlField;
    
    private string lolPageUrlField;
    
    private string fullTextField;
    
    private string clientIdField;
    
    private string titleField;
    
    private string descriptionField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string PictureId {
        get {
            return this.pictureIdField;
        }
        set {
            this.pictureIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Attribution {
        get {
            return this.attributionField;
        }
        set {
            this.attributionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string AttributionUrl {
        get {
            return this.attributionUrlField;
        }
        set {
            this.attributionUrlField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string PictureImageUrl {
        get {
            return this.pictureImageUrlField;
        }
        set {
            this.pictureImageUrlField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ThumbnailImageUrl {
        get {
            return this.thumbnailImageUrlField;
        }
        set {
            this.thumbnailImageUrlField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string UserId {
        get {
            return this.userIdField;
        }
        set {
            this.userIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string UserName {
        get {
            return this.userNameField;
        }
        set {
            this.userNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string PicturePageUrl {
        get {
            return this.picturePageUrlField;
        }
        set {
            this.picturePageUrlField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string TimeStamp {
        get {
            return this.timeStampField;
        }
        set {
            this.timeStampField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string LolId {
        get {
            return this.lolIdField;
        }
        set {
            this.lolIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string LolImageUrl {
        get {
            return this.lolImageUrlField;
        }
        set {
            this.lolImageUrlField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string LolPageUrl {
        get {
            return this.lolPageUrlField;
        }
        set {
            this.lolPageUrlField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string FullText {
        get {
            return this.fullTextField;
        }
        set {
            this.fullTextField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ClientId {
        get {
            return this.clientIdField;
        }
        set {
            this.clientIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Title {
        get {
            return this.titleField;
        }
        set {
            this.titleField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class CheezAPI {

    static public implicit operator List<LolsRandomPicture>(CheezAPI cheezApi) {
        if (cheezApi != null) {
            return new List<LolsRandomPicture>(cheezApi.Lols.Random);
        }
        else {
            return null;    
        }
    }
    static public implicit operator List<PicturesRandomPicture>(CheezAPI cheezApi) {
        if (cheezApi.Pictures != null) {
            return new List<PicturesRandomPicture>(cheezApi.Pictures.Random);
        }
        else {
            return null;  
        }

    }
    
    private Lols _itemLols;

    [System.Xml.Serialization.XmlElementAttribute("Lols", typeof(Lols), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public Lols Lols {
        get {
            return this._itemLols;
        }
        set {
            this._itemLols = (Lols)value;
        }
    }
    private Fail _itemFail;

    [System.Xml.Serialization.XmlElementAttribute("Fail", typeof(Fail), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public Fail Fail {
        get {
            return this._itemFail;
        }
        set {
            this._itemFail = (Fail)value;
        }
    }
    private Hai _itemHai;

    [System.Xml.Serialization.XmlElementAttribute("Hai", typeof(Hai), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public Hai Hai {
        get {
            return this._itemHai;
        }
        set {
            this._itemHai = (Hai)value;
        }
    }

    private Lol _itemLol;

    [System.Xml.Serialization.XmlElementAttribute("Lol", typeof(Lol), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public Lol Lol {
        get {
            return this._itemLol;
        }
        set {
            this._itemLol = (Lol)value;
        }
    }

    private Picture _itemPicture;

    [System.Xml.Serialization.XmlElementAttribute("Picture", typeof(Picture), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public Picture Picture {
        get {
            return this._itemPicture;
        }
        set {
            this._itemPicture = (Picture)value;
        }
    }

    private Pictures _itemPictures;

    [System.Xml.Serialization.XmlElementAttribute("Pictures", typeof(Pictures), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public Pictures Pictures {
        get {
            return this._itemPictures;
        }
        set {
            this._itemPictures = (Pictures)value;
        }
    }


}
