//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CheezburgerAPI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CheezburgerAPI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;Sites&gt;
        ///  &lt;Sites&gt;
        ///    &lt;Site&gt;
        ///      &lt;SiteId&gt;http://api.cheezburger.com/xml/site/1&lt;/SiteId&gt;
        ///      &lt;Name&gt;I Can Has Cheezburger?&lt;/Name&gt;
        ///      &lt;Url&gt;http://icanhascheezburger.com/&lt;/Url&gt;
        ///      &lt;Description&gt;Lolcats n Funny Pictures &lt;/Description&gt;
        ///      &lt;ShortDescription&gt;Lolcats&lt;/ShortDescription&gt;
        ///      &lt;SiteCategory&gt;LOL&lt;/SiteCategory&gt;
        ///      &lt;IsNSFW&gt;false&lt;/IsNSFW&gt;
        ///      &lt;IsNew&gt;false&lt;/IsNew&gt;
        ///      &lt;IsFeatureSite&gt;false&lt;/IsFeatureSite&gt;
        ///    &lt;/Site&gt;
        ///    &lt;Site&gt;
        ///      &lt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CheezSites {
            get {
                return ResourceManager.GetString("CheezSites", resourceCulture);
            }
        }
    }
}
